module.exports = {
    INVALID_REQUEST : "Invalid request",
    BAD_REQUEST:'Bad Request',
    OUT_OF_BOUND:'out of bound or invalid',
    INVALID_EMAIL: "Email invalid",
    USER_VERIFIED: "User verified successfully",
    USER_NOT_VERIFIED: "User email not verified",
    USER_NOT_EXIST: "user not exist",
    USER_EXIST: "user already exist",
    USER_CREATED: "user created successfully",
    USER_EDITED: "user edited successfully",
    INVALID_PASSWORD: "Inavlid Password",
    USER_LOGGED_OUT:'user logged out successfully',
    QUESTION_OPTION_EMPTY:'Option should not be empty',
    QUESTION_OPTIONS_REQUIRED:'Atlest 2 options are required',
    PASSWORD_DONT_MATCH: "Password dosen't match",
    PASSWORD_CHANGED: "password changed successfully",
    INTERNAL_SERVER_ERROR:'Internal Server Error',
    INVALID_CREDENTIALS:'invalid credentials',
    USER_LOGEDIN:'User Logged in sucessfully',
    TOKEN_REQUIRED:"An authentication token is required",
    INVALID_TOKEN:'Invalid token',
    NAME_REQUIRED:'User name is required',
    DATA_FETCHED:"data fetched sucessfully",
    CLASS_NOT_FOUND:"Class not found",
    NEW_CLASS_NOT_FOUND:"New class not found",
    CLASS_CREATED:'Class created successfully',
    FEILDS_MISSING:'Missing required fields',
    CLASS_UPDATED:'Class updated successfully',
CLASS_DELETED:'Class deleted successfully',
CLASS_FETCHED:'Class fetched successfully',
CLASS_MAXED:"Class is already at maximum capacity",
STUDENT_CREATED:"Student created successfully",
STUDENT_UPDATED:"Student updated successfully",
STUDENT_DELETED:"Student deleted successfully",
STUDENT_NOT_FOUND:'Student not found',
STUDENT_FETCHED:"Student fetched successfully",
TEACHER_CREATED:"Teacher created successfully",
TEACHER_UPDATED:"Teacher updated successfully",
TEACHER_DELETED:"Teacher deleted successfully",
TEACHER_NOT_FOUND:'Teacher not found',
TEACHER_FETCHED:"Teacher fetched successfully",
}